services:
  web:
    build: .
    command: gunicorn mysite.wsgi -b 0.0.0.0:8000
    volumes:
      - ./media:/usr/src/app/media 

  nginx:
    image: nginx:alpine 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      - ./static:/static  
      - ./media:/media    
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

